### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by 746443qjb** [SGGb0nd/step#2]
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/step-kit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/step-kit/
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <4.0,>=3.10; 0.2.0 Requires-Python <4.0,>=3.10; 0.2.1 Requires-Python <4.0,>=3.10; 0.2.2 Requires-Python <4.0,>=3.10
ERROR: Could not find a version that satisfies the requirement step-kit (from versions: none)
ERROR: No matching distribution found for step-kit

**Comment by SGGb0nd** [comment]
I thought this was a network issue. You can try to use a pypi mirror like tsinghua's which works for me. Also, you need to have a python installed with a version at least 3.10.

P.S. I've replied you at wechat with my contact info. You can check it there.
<img width="1896" alt="image" src="https://github.com/user-attachments/assets/f91bcc4a-901e-4d3c-987b-1740b4cb2549">
